############# Navegación en Español ##############

# menú principal
[[main]]
name = "Inicio"
url = "/"
weight = 1

[[main]]
name = "Acerca de"
url = "/about"
weight = 2

[[main]]
name = "Elementos"
url = "/elements"
weight = 3

[[main]]
weight = 4
name = "Páginas"

[[main]]
parent = "Páginas"
name = "Blog"
url = "/blog"

[[main]]
parent = "Páginas"
name = "Contacto"
url = "/contact"

[[main]]
parent = "Páginas"
name = "Autores"
url = "/authors"

[[main]]
parent = "Páginas"
name = "Categorías"
url = "/categories"

[[main]]
parent = "Páginas"
# name = "Página 404"
url = "/404"

# menú de pie de página
[[footer]]
name = "Acerca de"
url = "/about"
weight = 1

[[footer]]
name = "Elementos"
url = "/elements"
weight = 2

[[footer]]
name = "Política de Privacidad"
url = "/privacy-policy"
weight = 3